GET http://localhost:6606/todo
Accept: application/json

###
POST http://localhost:6606/todo
Content-Type: application/json

{
  "text": "Finish",
  "isCompleted": true,
  "isDeleted": false
}

###
DELETE http://localhost:6606/todo/63dc6d07b1741d414d667fc2
Accept: application/json

###
PUT http://localhost:6606/todo/63dc6d7db1741d414d667fca
Content-Type: application/json

{
  "text": "Finish!!!",
  "isCompleted": false,
  "isDeleted": false
}
###

PUT http://localhost:6606/todo/63dc6f20c797ed11d60310c4/complete
Content-Type: application/json

{
  "completed": true
}
